const FONTS = {
  font28_Bold: `
    font-size: 2.8rem;
    font-style: normal;
    font-weight: 700;
    line-height: 4.2rem;
    letter-spacing: -0.028rem;`,
  font24_Bold: `
    font-size: 2.4rem;
    font-style: normal;
    font-weight: 700;
    line-height: 3.6rem;
    letter-spacing: -0.024rem;`,
  font24_Regular: `
    font-size: 2.4rem;
    font-style: normal;
    font-weight: 400;
    line-height: 3.6rem;
    letter-spacing: -0.024rem;
  `,
  font20_Bold: `
    font-size: 2rem;
    font-style: normal;
    font-weight: 700;
    line-height: 3rem;
    letter-spacing: -0.02rem;`,
  font20_Regular: `
    font-size: 2rem;
    font-style: normal;
    font-weight: 400;
    line-height: 3rem;
    letter-spacing: -0.02rem;`,
  font18_Bold: `
    font-size: 1.8rem;
    font-style: normal;
    font-weight: 700;
    line-height: 2.8rem;
    letter-spacing: -0.018rem;`,
  font18_Regular: `
    font-size: 1.8rem;
    font-style: normal;
    font-weight: 400;
    line-height: 2.8rem;
    letter-spacing: -0.018rem;`,
  font16_Bold: `
    font-size: 1.6rem;
    font-style: normal;
    font-weight: 700;
    line-height: 2.6rem;
    letter-spacing: -0.016rem;`,
  font16_Regular: `
    font-size: 1.6rem;
    font-style: normal;
    font-weight: 400;
    line-height: 2.6rem;
    letter-spacing: -0.016rem;`,
  font15_Bold: `
    font-size: 1.5rem;
    font-style: normal;
    font-weight: 700;
    line-height: 2.2rem;
    letter-spacing: -0.015rem;`,
  font15_Regular: `
    font-size: 1.5rem;
    font-style: normal;
    font-weight: 400;
    line-height: 2.2rem;
    letter-spacing: -0.015rem;`,
  font14_Bold: `
    font-size: 1.4rem;
    font-style: normal;
    font-weight: 700;
    line-height: 2rem;
    letter-spacing: -0.007rem;`,
  font14_Regular: `
    font-size: 1.4rem;
    font-style: normal;
    font-weight: 400;
    line-height: 2rem;
    letter-spacing: -0.007rem;`,
  font12_Regular: `
    font-size: 1.2rem;
    font-style: normal;
    font-weight: 400;
    line-height: 1.8rem;
    letter-spacing: -0.006rem;`,
};

export default FONTS;
